// scoreplace.app — Release notes (lazy-loaded)
// Loaded on demand when the user opens "Notas de versões" in help modal.
//
// Convenção de versão (a partir de 30 Abr 2026): MAJOR.MINOR.PATCH-channel.
// Em beta, PATCH incrementa a cada release (1.0.3-beta → 1.0.4-beta).
// Histórico completo da fase alpha → beta exportado pra
// docs/scoreplace_relatorio_alpha_to_beta.docx (registro local do dono).

window._RELEASE_NOTES_HTML = (function () {
  var html =
    '<div style="margin-bottom:1rem;border:2px solid #fbbf24;border-radius:12px;padding:14px 16px;background:rgba(251,191,36,0.10);">' +
      '<div style="font-weight:800; color:#fbbf24; font-size:1rem; margin-bottom:8px;">📊 v1.0.18-beta <span style="color:var(--text-muted); font-weight:400; font-size:0.78rem;">(30 de Abril, 2026)</span></div>' +
      '<p><b>Gráfico "Movimento" agora segue o dia do plano focado.</b> Bug reportado: ao planejar ida pra amanhã, o gráfico de barras por hora não aparecia. Causa: <code>_hydrateAllPreferredMovement</code> usava sempre <code>dayKey(today)</code>, então plano-de-amanhã não tinha presenças hoje → <code>hasActivity=false</code> → bail silencioso. Agora o card focado (<code>state.focusedPreferred</code>) usa o <code>dayKey</code> da data de <code>startsAt</code> do plano. Cards não-focados continuam usando today (mais relevante pra browse). Header passa a "Movimento amanhã" / "Movimento em N dias" baseado em dia do plano vs hoje.</p>' +
      '<p><b>Sugestões do Google de volta em #place</b>. Bug reportado: quando havia PLANO ATIVO, seção "Sugestões do Google" sumia (até em São Paulo onde tem dezenas de venues). Causa-raiz: v1.0.15-beta trocou <code>locationBias</code> por <code>locationRestriction</code> achando que ambos aceitavam Circle. Mas no JS SDK do <code>Place.searchByText</code> (Places API New), <code>locationRestriction</code> SÓ aceita Bounds (rectangle); Circle silenciosamente quebra a query → 0 results. Voltei pra <code>locationBias</code> (que aceita Circle). A defesa contra "leaks geográficos" (ex: Brasil aparecendo pra Paris) agora vem do <b>filtro haversine client-side</b> que já estava em vigor desde v1.0.15 — Paris continua só vendo Paris.</p>' +
    '</div>' +
    '<div style="margin-bottom:1rem;border:2px solid #10b981;border-radius:12px;padding:14px 16px;background:rgba(16,185,129,0.10);">' +
      '<div style="font-weight:800; color:#34d399; font-size:1rem; margin-bottom:8px;">🔑 v1.0.17-beta <span style="color:var(--text-muted); font-weight:400; font-size:0.78rem;">(30 de Abril, 2026)</span></div>' +
      '<p><b>Magic link não pede digitar email novamente.</b> Bug reportado: usuária clicava no link recebido no celular mas o app pedia confirmar email — fricção desnecessária. Causa: <code>localStorage.scoreplace_emailForSignIn</code> só persiste no MESMO browser que pediu o link; cross-device (pediu desktop, abriu no celular) cai no <code>window.prompt()</code>. Fix: <code>actionCodeSettings.url</code> agora inclui <code>?eml=&lt;email&gt;</code> codificado. Em <code>_completeEmailLinkSignIn</code>, fallback chain: localStorage → URL param → prompt. Funciona cross-device sem fricção.</p>' +
      '<p><b>Landing CTA: texto trocado.</b> Era "Crie seu torneio grátis" — gerava dúvida sobre o que o botão fazia (cadastro? login? criar?). Agora "Entrar no scoreplace.app" — claro e direto. Em inglês: "Sign in to scoreplace.app".</p>' +
      '<p><b>SMS login: mensagens de erro específicas com código.</b> Bug reportado: "SMS não mandou pra ninguém". Sem error.code visível, impossível diagnosticar. Agora cada caso tem mensagem específica: <code>operation-not-allowed</code> (provider não habilitado no Firebase), <code>too-many-requests</code> (cota), <code>quota-exceeded</code> (free tier), <code>captcha-check-failed</code>, <code>invalid-phone-number</code>, etc. Todas sugerem fallback "Use Link Mágico por E-mail". Sentry continua capturando pra investigação retroativa.</p>' +
    '</div>' +
    '<div style="margin-bottom:1rem;border:2px solid #8b5cf6;border-radius:12px;padding:14px 16px;background:rgba(139,92,246,0.10);">' +
      '<div style="font-weight:800; color:#a78bfa; font-size:1rem; margin-bottom:8px;">🪪 v1.0.16-beta <span style="color:var(--text-muted); font-weight:400; font-size:0.78rem;">(30 de Abril, 2026)</span></div>' +
      '<p><b>Mudança de nome no perfil propaga imediatamente em toda a UI</b>. Bug reportado: usuário mudou de "topi3838" pra "Toninho" no perfil, welcome card mostrava "Bem-vindo, Toninho!" mas o topbar (canto superior direito) continuava com "topi3838". Causa-raiz: o nome no topbar vinha de <code>firebase.auth().currentUser.displayName</code> (Firebase Auth, sincronizado com Google OAuth no primeiro login) enquanto o welcome card vinha de <code>AppStore.currentUser.displayName</code> (merged do Firestore). Quando <code>simulateLoginSuccess</code> re-rodava (token refresh, onAuthStateChanged), passava o user do Firebase Auth com nome STALE, revertendo o topbar.</p>' +
      '<p>Fix em 2 camadas: (1) <code>saveUserProfile</code> agora chama <code>firebase.auth().currentUser.updateProfile({displayName, photoURL})</code> após salvar no Firestore — sincroniza Firebase Auth com Firestore como single source of truth. (2) <code>_updateTopbarForUser</code> defensivo: se uid bate, prefere <code>AppStore.currentUser.displayName</code> sobre o user passado como parâmetro. Belt-and-suspenders pra caso (1) falhe.</p>' +
    '</div>' +
    '<div style="margin-bottom:1rem;border:2px solid #06b6d4;border-radius:12px;padding:14px 16px;background:rgba(6,182,212,0.10);">' +
      '<div style="font-weight:800; color:#22d3ee; font-size:1rem; margin-bottom:8px;">🌍 v1.0.15-beta <span style="color:var(--text-muted); font-weight:400; font-size:0.78rem;">(30 de Abril, 2026)</span></div>' +
      '<p><b>Sugestões do Google estritamente dentro do raio.</b> Bug reportado: usuária em Paris recebia quadras a 7000km+ no Brasil. Causa-raiz tripla na chamada <code>Place.searchByText</code>: (1) <code>region: "br"</code> hardcoded biaseava ALL searches pra Brasil; (2) <code>locationBias</code> é SOFT — Google retorna venues fora se forem populares globalmente; (3) <code>language: "pt-BR"</code> favorecia results em português. Fix: trocado pra <code>locationRestriction</code> (Circle, HARD), removidos hardcoded region/language. Defesa-em-camada client-side: <code>haversineKm</code> filtra qualquer leak >raioKm.</p>' +
      '<p><b>Convite de amizade não aparece mais duplicado em "Convites Pendentes".</b> Bug reportado: convidei amigo, aparece 2 cards iguais. Causa: destinatário tinha 2 user docs no Firestore (legacy email-keyed pré-migração + atual uid-keyed). Ambos os ids ficavam em <code>friendRequestsSent</code>, cada um carregava profile separado. Fix em <code>_renderSentRequests</code>: agrupa profiles por email, escolhe o doc cujo id NÃO parece email (uid real). Botão ✕ chama novo <code>_cancelFriendRequestMulti</code> que cancela todos os uids do grupo de uma vez. Bonus: dedup defensivo em <code>_sendFriendRequest</code> pra prevenir push duplicado em double-tap rápido.</p>' +
    '</div>' +
    '<div style="margin-bottom:1rem;border:2px solid #fbbf24;border-radius:12px;padding:14px 16px;background:rgba(251,191,36,0.10);">' +
      '<div style="font-weight:800; color:#fbbf24; font-size:1rem; margin-bottom:8px;">📬 v1.0.14-beta <span style="color:var(--text-muted); font-weight:400; font-size:0.78rem;">(30 de Abril, 2026)</span></div>' +
      '<p><b>Magic link: painel persistente "verifique seu spam".</b> Bug reportado: usuário recebeu o link mas foi pra spam, e a toast efêmera com "(e spam)" sumiu rápido demais. Agora, após enviar o link, o modal-login é substituído por um painel persistente com ícone 📬, mensagem "Link enviado!", o e-mail do destinatário em destaque, um aviso âmbar grande "<b>⚠️ Não chegou? Cheque o spam</b>" + indicação do remetente <code>noreply@scoreplace-app.firebaseapp.com</code> pra adicionar aos contatos. Painel fica até o usuário fechar manualmente. Botões: Fechar / Reenviar.</p>' +
    '</div>' +
    '<div style="margin-bottom:1rem;border:2px solid #f97316;border-radius:12px;padding:14px 16px;background:rgba(249,115,22,0.10);">' +
      '<div style="font-weight:800; color:#fb923c; font-size:1rem; margin-bottom:8px;">🌍 v1.0.13-beta <span style="color:var(--text-muted); font-weight:400; font-size:0.78rem;">(30 de Abril, 2026)</span></div>' +
      '<p><b>Erro do login Google agora mostra código + sugestão específica de workaround.</b> Antes era sempre "Não foi possível realizar o login com Google" sem indicar o problema. Bug reportado: usuária em Paris recebeu erro genérico, sem direção do que tentar. Mensagens novas:</p>' +
      '<ul style="margin:0 0 0 1.2rem; padding:0; font-size:0.82rem;">' +
        '<li><code>auth/network-request-failed</code> → "Sem conexão estável com Google. Tente Wi-Fi ou outra rede."</li>' +
        '<li><code>auth/too-many-requests</code> → "Muitas tentativas. Aguarde alguns minutos."</li>' +
        '<li><code>auth/internal-error</code> → "Erro interno do Firebase. Tente novamente em instantes."</li>' +
        '<li><code>auth/unauthorized-domain</code> → "Reporte: scoreplace.app@gmail.com"</li>' +
        '<li><code>auth/user-disabled</code> → "Conta desativada. Contate suporte."</li>' +
        '<li><code>auth/operation-not-allowed</code> → "Login Google indisponível no momento."</li>' +
        '<li>outro → mensagem genérica + código pra debug</li>' +
      '</ul>' +
      '<p>Todas as mensagens incluem fallback "Use SMS ou Link Mágico abaixo" — usuário com Google bloqueado não fica sem caminho. Sentry continua capturando o erro com contexto pra investigação retroativa.</p>' +
    '</div>' +
    '<div style="margin-bottom:1rem;border:2px solid #ef4444;border-radius:12px;padding:14px 16px;background:rgba(239,68,68,0.10);">' +
      '<div style="font-weight:800; color:#ef4444; font-size:1rem; margin-bottom:8px;">🔐 v1.0.12-beta <span style="color:var(--text-muted); font-weight:400; font-size:0.78rem;">(30 de Abril, 2026)</span></div>' +
      '<p><b>3 bugs de login conectados, 1 fix consolidado</b>:</p>' +
      '<p>(1) <b>Termos pedidos a cada novo login mesmo de usuário cadastrado</b>: terms-gate em simulateLoginSuccess agora usa <code>existingProfile</code> (retorno raw do <code>firebase-db.loadUserProfile</code>) PRIMEIRO em vez de <code>currentUser</code>. Causa-raiz: race entre o merge em <code>store.js.loadUserProfile</code> e a checagem — se o merge não tinha completado, <code>currentUser.acceptedTerms</code> ficava undefined apesar do Firestore ter <code>true</code>. Fallback pra currentUser caso existingProfile seja null. Diagnóstico completo via <code>console.log</code> com versão pra cada checagem (<code>existingProfile_*</code>, <code>currentUser_*</code>, <code>needsAcceptance</code>).</p>' +
      '<p>(2) <b>Modal de login não some após Google login (Safari)</b>: simulateLoginSuccess agora usa <code>_forceCloseLoginModal()</code> (mais agressivo: classList.remove + style.display=none por 50ms + revert) em vez de só <code>classList.remove(\'active\')</code> no fim do flow.</p>' +
      '<p>(3) <b>Tela de login volta toda vez que salva o perfil</b>: provável consequência do (2) — modal-login fica com <code>.active</code> escondido atrás do modal-profile, fica visível quando profile fecha. Adicionada chamada defensiva <code>_forceCloseLoginModal()</code> em <code>saveUserProfile</code> logo depois do close do profile, pra garantir que mesmo se (2) regredir, (3) não recorre.</p>' +
    '</div>' +
    '<div style="margin-bottom:1rem;border:2px solid #6366f1;border-radius:12px;padding:14px 16px;background:rgba(99,102,241,0.12);">' +
      '<div style="font-weight:800; color:#a5b4fc; font-size:1rem; margin-bottom:8px;">📡 v1.0.11-beta <span style="color:var(--text-muted); font-weight:400; font-size:0.78rem;">(30 de Abril, 2026)</span></div>' +
      '<p><b>Raio de busca em #place agora default 25km</b> (era 10km) — cobre cidades metropolitanas brasileiras tipicas. Bug reportado: usuário cadastrou venue novo, voltou pro #place, não viu o card aparecer. Causa: filtro de distância 10km excluía o venue (provavelmente noutra parte da cidade). Ajuste manual do raio é preservado em <code>localStorage.scoreplace_venues_filters</code>.</p>' +
      '<p><b>Empty state da seção "Outros locais" com diagnóstico inteligente</b>. Quando a seção fica vazia, agora diferencia 2 casos: (a) <i>tem N venues cadastrados fora do raio atual</i> → mostra contador + botão "📡 Expandir pra 50km" que dobra o raio e re-filtra (sem reload); (b) <i>nenhum venue na região</i> → mantém CTA "+ Cadastrar local". Resolve a confusão "cadastrei mas não aparece".</p>' +
    '</div>' +
    '<div style="margin-bottom:1rem;border:2px solid #a5b4fc;border-radius:12px;padding:14px 16px;background:rgba(99,102,241,0.10);">' +
      '<div style="font-weight:800; color:#a5b4fc; font-size:1rem; margin-bottom:8px;">🏢 v1.0.10-beta <span style="color:var(--text-muted); font-weight:400; font-size:0.78rem;">(30 de Abril, 2026)</span></div>' +
      '<p><b>Seção "🏢 Outros locais no scoreplace" sempre visível em #place.</b> Antes a seção tinha early-exit quando <code>spResults.length === 0</code> — usuário com PLANO ATIVO ativo via gap direto pra "📍 Sugestões do Google", sem entender se o app tinha banco próprio de venues. Agora o header sempre aparece. Quando vazio, mostra empty state explicando + CTA "+ Cadastrar local" linkando direto pra <code>#my-venues</code>. Resolve a fricção reportada: "deveria aparecer os locais cadastrados entre o plano ativo e os locais do google".</p>' +
    '</div>' +
    '<div style="margin-bottom:1rem;border:2px solid #fbbf24;border-radius:12px;padding:14px 16px;background:rgba(251,191,36,0.12);">' +
      '<div style="font-weight:800; color:#fbbf24; font-size:1rem; margin-bottom:8px;">🎾 v1.0.9-beta <span style="color:var(--text-muted); font-weight:400; font-size:0.78rem;">(30 de Abril, 2026)</span></div>' +
      '<p><b>CTA "Cadastrar quadras" inline no gráfico de movimento.</b> Quando o gráfico está em escala estimada (local sem <code>courts[]</code> cadastrados), agora aparece um aviso âmbar abaixo das barras: <i>"⚠️ Escala estimada — local sem quadras cadastradas. [🎾 Cadastrar quadras →]"</i>. Clique direciona pra <code>#my-venues</code> com nome/lat/lon do venue pré-stashed via <code>sessionStorage</code> (mesmo padrão do <code>_venuesRegisterPlace</code>). Resolve a fricção reportada: usuário via dado errado mas não tinha caminho visível pra cadastrar — só via "+ Cadastrar local" lá embaixo de #place ou hash direto. Pra preferreds com synthetic pid (<code>pref_lat_lng</code>), extrai lat/lon do próprio pid pra pré-popular.</p>' +
    '</div>' +
    '<div style="margin-bottom:1rem;border:2px solid #fbbf24;border-radius:12px;padding:14px 16px;background:rgba(251,191,36,0.08);">' +
      '<div style="font-weight:800; color:#fbbf24; font-size:1rem; margin-bottom:8px;">v1.0.8-beta <span style="color:var(--text-muted); font-weight:400; font-size:0.78rem;">(30 de Abril, 2026)</span></div>' +
      '<p><b>Gráfico de movimento "Movimento hoje" não enche barra inteira com 1 pessoa.</b> Bug reportado: 1 pessoa em local sem quadras cadastradas (ou com placeId synthetic não-Google) renderizava barra de 100% — visualmente "lotado" quando deveria parecer "vazio". A v0.16.49 introduziu escala absoluta por capacidade do venue (<code>sum(courts.count) × 4</code>) mas o fallback (quando capacity=0) era max-bucket-relative — 1 pessoa = max = 100%. Agora fallback usa <b>baseline mínimo de 16</b> (4 quadras × 4 jogadores, venue pequeno típico): 1 pessoa ≈ 6% bar. Quando há pico maior que o baseline, expande pra acomodar — pico fica em 100%, demais escalonam proporcional. Tooltip da barra mostra "(escala estimada — local sem quadras cadastradas)" pra ser transparente sobre o estimativa.</p>' +
    '</div>' +
    '<div style="margin-bottom:1rem;border:2px solid #f59e0b;border-radius:12px;padding:14px 16px;background:rgba(245,158,11,0.08);">' +
      '<div style="font-weight:800; color:#f59e0b; font-size:1rem; margin-bottom:8px;">🎯 v1.0.7-beta <span style="color:var(--text-muted); font-weight:400; font-size:0.78rem;">(30 de Abril, 2026)</span></div>' +
      '<p><b>Profile completion nudge mais convidativo na dashboard.</b> Antes só aparecia pra quem já tinha torneios e checava 2 campos (cidade, modalidades). Agora aparece pra todos os logged-in users e cobre os <b>4 campos críticos</b>: <i>sexo, data de nascimento, cidade, modalidades</i>. Sexo e nascimento permitem auto-categorização ao se inscrever em torneios (ex: torneios femininos ou por faixa etária). Banner ganhou: ícone 🎯, mensagem com tempo estimado ("em ~30s"), <b>contador de progresso</b> ("3 de 4 campos") e <b>barra visual</b> com gradient âmbar mostrando quanto falta. Botão CTA mais firme ("Completar →"). Continua dismissível por sessão; reaparece se ainda há campos faltando no próximo login. Sobre soak automático do Google: deferido pra v2 — exige Verificação formal Google (4-6 semanas) pros scopes restritos <code>user.gender.read</code>, <code>user.birthday.read</code>, <code>user.addresses.read</code>.</p>' +
    '</div>' +
    '<div style="margin-bottom:1rem;border:2px solid #06b6d4;border-radius:12px;padding:14px 16px;background:rgba(6,182,212,0.08);">' +
      '<div style="font-weight:800; color:#06b6d4; font-size:1rem; margin-bottom:8px;">v1.0.6-beta <span style="color:var(--text-muted); font-weight:400; font-size:0.78rem;">(30 de Abril, 2026)</span></div>' +
      '<p><b>Excluir conta volta pra landing page.</b> Antes ficava preso no loader 🎾 "Carregando..." indefinidamente — o router via <code>currentUser=null</code> mas <code>localStorage.scoreplace_authCache</code> continuava presente, caindo no branch que espera auth resolver (que nunca vai resolver, porque a conta foi excluída). Fix: limpar cache de auth + IndexedDB do Firebase logo depois do delete success, antes do <code>initRouter()</code>. Router agora vê <code>loggedIn=false + hasCache=false</code> → renderiza a landing.</p>' +
    '</div>' +
    '<div style="margin-bottom:1rem;border:2px solid #ef4444;border-radius:12px;padding:14px 16px;background:rgba(239,68,68,0.08);">' +
      '<div style="font-weight:800; color:#ef4444; font-size:1rem; margin-bottom:8px;">🔒 v1.0.5-beta <span style="color:var(--text-muted); font-weight:400; font-size:0.78rem;">(30 de Abril, 2026)</span></div>' +
      '<p><b>Correção de privacidade — telefone, data de nascimento, sexo e endereço dos usuários não vazam mais por busca de amigos.</b> A função <code>searchUsers</code> em #explore retornava o documento inteiro do perfil de cada usuário (incluindo phone, birthDate, gender, preferredCeps, preferredLocations) — qualquer um podia abrir DevTools e dumpar dados pessoais via console. Agora a busca retorna só campos públicos: nome, e-mail, foto, modalidades, timestamps. Fix client-side imediato; fix definitivo nas Firestore Security Rules vai num round dedicado com testes.</p>' +
      '<p><b>"Esportes Preferidos" agora se chama "Modalidades"</b> no perfil. Mais curto e alinhado com a nomenclatura usada no resto do app.</p>' +
      '<p><b>Pills de Modalidades, Presença e Aparência (temas) parecem corretamente desativadas por padrão.</b> Antes nasciam com o estilo default do <code>.btn</code> (texto branco, sem bg explícito) que parecia "todos selecionados" até o JS rodar e sobrescrever. Agora cada pill já nasce com inline style "desativado" (transparente, texto muted, borda discreta) — o JS só ativa o que foi escolhido.</p>' +
      '<p><b>Toggles de notificação iniciam com os 3 ativos.</b> Antes "todas" começava ON e "importantes/fundamentais" OFF, criando um flash visual antes da cascata corrigir pra "tudo ativo". Agora os 3 já nascem ON, alinhados com o default canônico (<code>todas</code> = receber tudo).</p>' +
      '<p><b>Sobre puxar Sexo/Nascimento/Cidade do Google:</b> tecnicamente possível mas exige scopes restritos (<code>user.gender.read</code>, <code>user.birthday.read</code>, <code>user.phonenumbers.read</code>) que precisam de Google App Verification (4-6 semanas, exige privacy policy revisada e demo video). Fica deferido — campos seguem manuais.</p>' +
    '</div>' +
    '<div style="margin-bottom:1rem;border:2px solid #34d399;border-radius:12px;padding:14px 16px;background:rgba(52,211,153,0.08);">' +
      '<div style="font-weight:800; color:#34d399; font-size:1rem; margin-bottom:8px;">v1.0.4-beta <span style="color:var(--text-muted); font-weight:400; font-size:0.78rem;">(30 de Abril, 2026)</span></div>' +
      '<p><b>Sentry observability — round 1 de cleanup.</b> Auditoria das 7 issues unresolved abriu 6 fixes consolidados num commit: (1) skip de init em ambiente não-produção (mata 13 events do Karma E2E poluindo Sentry); (2) <code>release</code> lazy via <code>beforeSend</code> (corrige <code>scoreplace@unknown</code> em eventos disparados antes do <code>store.js</code> defer carregar); (3) <code>.catch()</code> em <code>reg.update()</code> do Service Worker (mata <code>TypeError: Script sw.js load failed</code> em iOS Safari com rede móvel ruim); (4) probe <code>_captureMessage(\'login modal force-closed\')</code> removido (era diagnóstico da v0.17.83-91, cumpriu papel, agora só polui — 36 events em 2d sem sinal); (5) <code>ignoreErrors</code> ganha 4 patterns: <code>Script .* load failed</code>, <code>popup has been closed</code>, <code>popup_closed_by_user</code>, <code>Test event from beta-readiness</code>.</p>' +
      '<p><b>Hamburger não pisca mais na 1ª vez.</b> Bug reproduzido via Chrome MCP: usuário abria menu logo após page load, Firestore listener disparava <code>onSnapshot</code> nos primeiros 0.5-2s, <code>_softRefreshView()</code> chamava <code>initRouter()</code>, e <code>router.js:84</code> fechava o menu unconditionally em todo handleRoute. Stack trace pegou em flagrante. Fix: <code>_closeHamburger</code> só dispara em navegação real (<code>!window._isSoftRefresh</code>); soft refresh re-renderiza a mesma view e não justifica fechar menu aberto.</p>' +
      '<p><b>Botões "🤖 Add Bot" e "🗑️ Apagar" removidos do detalhe do torneio.</b> Eram úteis em alpha pra testar fluxos de chaveamento e descartar dados de teste. Em beta, bots inflavam dados reais sem motivo e delete destrutivo num clique era arriscado demais. Funções <code>addBotsFunction</code> e <code>deleteTournamentFunction</code> permanecem definidas (zero impacto no usuário) — só perderam o ponto de entrada na UI.</p>' +
    '</div>' +
    '<div style="margin-bottom:1rem;border:2px solid #10b981;border-radius:12px;padding:14px 16px;background:rgba(16,185,129,0.08);">' +
      '<div style="font-weight:800; color:#10b981; font-size:1rem; margin-bottom:8px;">v1.0.3-beta <span style="color:var(--text-muted); font-weight:400; font-size:0.78rem;">(30 de Abril, 2026)</span></div>' +
      '<p><b>Convenção de versão padronizada</b> — antes era <code>1.0.0-beta-N</code>, agora <code>1.0.N-beta</code> (semver clássico). PATCH incrementa a cada deploy. Trocas internas; nada visual ou funcional muda pro usuário.</p>' +
      '<p><b>Auditoria completa de hints + manual</b>: ~120 hints validados contra o app atual. Removidos refs obsoletos (Suíço como formato principal, "4 pilares" → "5 pilares" + Stats, Place unificado). Adicionados hints novos (página #invite, página #support, modal de aceite de Termos). Nova seção <b>"💚 Apoio e Suporte"</b> no manual com PIX, Plano Pro, reportar bugs, convidar amigos, Privacy+Termos.</p>' +
    '</div>' +
    '<div style="margin-bottom:1rem;border:2px solid #fbbf24;border-radius:12px;padding:14px 16px;background:rgba(251,191,36,0.08);">' +
      '<div style="font-weight:800; color:#fbbf24; font-size:1.1rem; margin-bottom:8px;">🚀 v1.0.0-beta <span style="color:var(--text-muted); font-weight:400; font-size:0.78rem;">(29 de Abril, 2026)</span></div>' +
      '<p><b>BETA LANÇADO!</b> O scoreplace.app oficialmente saiu da fase de desenvolvimento exploratório e entrou em <b>beta soft</b>. <b>O que muda:</b> dados são reais, persistem, e qualquer mudança destrutiva exige comunicação prévia. <b>Reset de transição:</b> banco zerado pra começar limpo. <b>Critérios de saída atingidos:</b> Performance Lighthouse 64, Acessibilidade 96, 34 testes E2E, Sentry ativo, Backup Firestore diário, Quotas+alertas, Privacy+Termos publicados, 0 erros JS no smoke. Reportar bugs: scoreplace.app@gmail.com com screenshot. Bora jogar! 🎾🏆</p>' +
    '</div>';
  return html;
})();
